class Transaction {
  final String id;
  final String title;
  final double value;
  final String? description;
  final DateTime date;
  final String? categoryId;

  Transaction({
    required this.id,
    required this.title,
    required this.value,
    this.description,
    required this.date,
    this.categoryId,
  });
}

final List<Transaction> dummyTransactions = [
  // Food (10)
  Transaction(
    id: 'food1',
    title: 'Café',
    value: 6.50,
    date: DateTime.now().subtract(Duration(days: 0)),
    categoryId: 'food',
  ),
  Transaction(
    id: 'food2',
    title: 'Almoço',
    value: 22.30,
    date: DateTime.now().subtract(Duration(days: 1)),
    categoryId: 'food',
  ),
  Transaction(
    id: 'food3',
    title: 'Jantar',
    value: 45.00,
    date: DateTime.now().subtract(Duration(days: 2)),
    categoryId: 'food',
  ),
  Transaction(
    id: 'food4',
    title: 'Lanche',
    value: 12.00,
    date: DateTime.now().subtract(Duration(days: 3)),
    categoryId: 'food',
  ),
  Transaction(
    id: 'food5',
    title: 'Supermercado',
    value: 150.75,
    date: DateTime.now().subtract(Duration(days: 4)),
    categoryId: 'food',
  ),
  Transaction(
    id: 'food6',
    title: 'Padaria',
    value: 8.90,
    date: DateTime.now().subtract(Duration(days: 5)),
    categoryId: 'food',
  ),
  Transaction(
    id: 'food7',
    title: 'Delivery',
    value: 39.20,
    date: DateTime.now().subtract(Duration(days: 6)),
    categoryId: 'food',
  ),
  Transaction(
    id: 'food8',
    title: 'Bebidas',
    value: 18.00,
    date: DateTime.now().subtract(Duration(days: 7)),
    categoryId: 'food',
  ),
  Transaction(
    id: 'food9',
    title: 'Mercado Hortifruti',
    value: 62.10,
    date: DateTime.now().subtract(Duration(days: 8)),
    categoryId: 'food',
  ),
  Transaction(
    id: 'food10',
    title: 'Restaurante',
    value: 88.40,
    date: DateTime.now().subtract(Duration(days: 9)),
    categoryId: 'food',
  ),

  // Transport (10)
  Transaction(
    id: 'transport1',
    title: 'Combustível',
    value: 120.00,
    date: DateTime.now().subtract(Duration(days: 10)),
    categoryId: 'transport',
  ),
  Transaction(
    id: 'transport2',
    title: 'Táxi',
    value: 35.50,
    date: DateTime.now().subtract(Duration(days: 11)),
    categoryId: 'transport',
  ),
  Transaction(
    id: 'transport3',
    title: 'Uber',
    value: 28.70,
    date: DateTime.now().subtract(Duration(days: 12)),
    categoryId: 'transport',
  ),
  Transaction(
    id: 'transport4',
    title: 'Bilhete Ônibus',
    value: 4.40,
    date: DateTime.now().subtract(Duration(days: 13)),
    categoryId: 'transport',
  ),
  Transaction(
    id: 'transport5',
    title: 'Estacionamento',
    value: 12.00,
    date: DateTime.now().subtract(Duration(days: 14)),
    categoryId: 'transport',
  ),
  Transaction(
    id: 'transport6',
    title: 'Manutenção Carro',
    value: 300.00,
    date: DateTime.now().subtract(Duration(days: 15)),
    categoryId: 'transport',
  ),
  Transaction(
    id: 'transport7',
    title: 'Peças',
    value: 85.99,
    date: DateTime.now().subtract(Duration(days: 16)),
    categoryId: 'transport',
  ),
  Transaction(
    id: 'transport8',
    title: 'Lavagem',
    value: 25.00,
    date: DateTime.now().subtract(Duration(days: 17)),
    categoryId: 'transport',
  ),
  Transaction(
    id: 'transport9',
    title: 'IPVA',
    value: 600.00,
    date: DateTime.now().subtract(Duration(days: 18)),
    categoryId: 'transport',
  ),
  Transaction(
    id: 'transport10',
    title: 'Pedágio',
    value: 9.20,
    date: DateTime.now().subtract(Duration(days: 19)),
    categoryId: 'transport',
  ),

  // Health (10)
  Transaction(
    id: 'health1',
    title: 'Consulta Médica',
    value: 120.00,
    date: DateTime.now().subtract(Duration(days: 20)),
    categoryId: 'health',
  ),
  Transaction(
    id: 'health2',
    title: 'Remédio',
    value: 32.50,
    date: DateTime.now().subtract(Duration(days: 21)),
    categoryId: 'health',
  ),
  Transaction(
    id: 'health3',
    title: 'Exames',
    value: 200.00,
    date: DateTime.now().subtract(Duration(days: 22)),
    categoryId: 'health',
  ),
  Transaction(
    id: 'health4',
    title: 'Fisioterapia',
    value: 75.00,
    date: DateTime.now().subtract(Duration(days: 23)),
    categoryId: 'health',
  ),
  Transaction(
    id: 'health5',
    title: 'Vacina',
    value: 95.00,
    date: DateTime.now().subtract(Duration(days: 24)),
    categoryId: 'health',
  ),
  Transaction(
    id: 'health6',
    title: 'Óculos',
    value: 250.00,
    date: DateTime.now().subtract(Duration(days: 25)),
    categoryId: 'health',
  ),
  Transaction(
    id: 'health7',
    title: 'Dentista',
    value: 180.00,
    date: DateTime.now().subtract(Duration(days: 26)),
    categoryId: 'health',
  ),
  Transaction(
    id: 'health8',
    title: 'Suplementos',
    value: 89.90,
    date: DateTime.now().subtract(Duration(days: 27)),
    categoryId: 'health',
  ),
  Transaction(
    id: 'health9',
    title: 'Psicólogo',
    value: 150.00,
    date: DateTime.now().subtract(Duration(days: 28)),
    categoryId: 'health',
  ),
  Transaction(
    id: 'health10',
    title: 'Clínica',
    value: 220.00,
    date: DateTime.now().subtract(Duration(days: 29)),
    categoryId: 'health',
  ),

  // Education (10)
  Transaction(
    id: 'education1',
    title: 'Curso Online',
    value: 59.90,
    date: DateTime.now().subtract(Duration(days: 30)),
    categoryId: 'education',
  ),
  Transaction(
    id: 'education2',
    title: 'Livro',
    value: 45.00,
    date: DateTime.now().subtract(Duration(days: 31)),
    categoryId: 'education',
  ),
  Transaction(
    id: 'education3',
    title: 'Material Escolar',
    value: 32.20,
    date: DateTime.now().subtract(Duration(days: 32)),
    categoryId: 'education',
  ),
  Transaction(
    id: 'education4',
    title: 'Mensalidade',
    value: 800.00,
    date: DateTime.now().subtract(Duration(days: 33)),
    categoryId: 'education',
  ),
  Transaction(
    id: 'education5',
    title: 'Palestra',
    value: 120.00,
    date: DateTime.now().subtract(Duration(days: 34)),
    categoryId: 'education',
  ),
  Transaction(
    id: 'education6',
    title: 'Workshop',
    value: 200.00,
    date: DateTime.now().subtract(Duration(days: 35)),
    categoryId: 'education',
  ),
  Transaction(
    id: 'education7',
    title: 'Certificação',
    value: 350.00,
    date: DateTime.now().subtract(Duration(days: 36)),
    categoryId: 'education',
  ),
  Transaction(
    id: 'education8',
    title: 'Tutor',
    value: 90.00,
    date: DateTime.now().subtract(Duration(days: 37)),
    categoryId: 'education',
  ),
  Transaction(
    id: 'education9',
    title: 'Software Educacional',
    value: 29.99,
    date: DateTime.now().subtract(Duration(days: 38)),
    categoryId: 'education',
  ),
  Transaction(
    id: 'education10',
    title: 'Inscrição',
    value: 45.00,
    date: DateTime.now().subtract(Duration(days: 39)),
    categoryId: 'education',
  ),

  // Leisure (10)
  Transaction(
    id: 'leisure1',
    title: 'Cinema',
    value: 28.00,
    date: DateTime.now().subtract(Duration(days: 40)),
    categoryId: 'leisure',
  ),
  Transaction(
    id: 'leisure2',
    title: 'Academia',
    value: 120.00,
    date: DateTime.now().subtract(Duration(days: 41)),
    categoryId: 'leisure',
  ),
  Transaction(
    id: 'leisure3',
    title: 'Show',
    value: 180.00,
    date: DateTime.now().subtract(Duration(days: 42)),
    categoryId: 'leisure',
  ),
  Transaction(
    id: 'leisure4',
    title: 'Parque',
    value: 15.00,
    date: DateTime.now().subtract(Duration(days: 43)),
    categoryId: 'leisure',
  ),
  Transaction(
    id: 'leisure5',
    title: 'Viagem',
    value: 720.00,
    date: DateTime.now().subtract(Duration(days: 44)),
    categoryId: 'leisure',
  ),
  Transaction(
    id: 'leisure6',
    title: 'Bar',
    value: 95.00,
    date: DateTime.now().subtract(Duration(days: 45)),
    categoryId: 'leisure',
  ),
  Transaction(
    id: 'leisure7',
    title: 'Museu',
    value: 20.00,
    date: DateTime.now().subtract(Duration(days: 46)),
    categoryId: 'leisure',
  ),
  Transaction(
    id: 'leisure8',
    title: 'Passeio',
    value: 60.00,
    date: DateTime.now().subtract(Duration(days: 47)),
    categoryId: 'leisure',
  ),
  Transaction(
    id: 'leisure9',
    title: 'Evento',
    value: 130.00,
    date: DateTime.now().subtract(Duration(days: 48)),
    categoryId: 'leisure',
  ),
  Transaction(
    id: 'leisure10',
    title: 'Aula de Dança',
    value: 70.00,
    date: DateTime.now().subtract(Duration(days: 49)),
    categoryId: 'leisure',
  ),

  // Shopping (10)
  Transaction(
    id: 'shopping1',
    title: 'Celular',
    description: 'Compra online',
    value: 1365.12,
    date: DateTime.now().subtract(Duration(days: 50)),
    categoryId: 'shopping',
  ),
  Transaction(
    id: 'shopping2',
    title: 'Notebook',
    value: 2823.91,
    date: DateTime.now().subtract(Duration(days: 51)),
    categoryId: 'shopping',
  ),
  Transaction(
    id: 'shopping3',
    title: 'Mouse',
    value: 63.37,
    date: DateTime.now().subtract(Duration(days: 52)),
    categoryId: 'shopping',
  ),
  Transaction(
    id: 'shopping4',
    title: 'Mausepad',
    value: 23.45,
    date: DateTime.now().subtract(Duration(days: 53)),
    categoryId: 'shopping',
  ),
  Transaction(
    id: 'shopping5',
    title: 'Monitor',
    value: 845.75,
    date: DateTime.now().subtract(Duration(days: 54)),
    categoryId: 'shopping',
  ),
  Transaction(
    id: 'shopping6',
    title: 'Teclado',
    value: 325.68,
    date: DateTime.now().subtract(Duration(days: 55)),
    categoryId: 'shopping',
  ),
  Transaction(
    id: 'shopping7',
    title: 'Camiseta',
    value: 49.90,
    date: DateTime.now().subtract(Duration(days: 56)),
    categoryId: 'shopping',
  ),
  Transaction(
    id: 'shopping8',
    title: 'Tênis',
    value: 199.99,
    date: DateTime.now().subtract(Duration(days: 57)),
    categoryId: 'shopping',
  ),
  Transaction(
    id: 'shopping9',
    title: 'Relógio',
    value: 499.00,
    date: DateTime.now().subtract(Duration(days: 58)),
    categoryId: 'shopping',
  ),
  Transaction(
    id: 'shopping10',
    title: 'Acessórios',
    value: 59.90,
    date: DateTime.now().subtract(Duration(days: 59)),
    categoryId: 'shopping',
  ),
];
