name: myfinance_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

config_name:
  name: "My Finance"

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.png"

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  uuid: ^4.5.3
  google_fonts: ^8.1.0
  fl_chart: ^1.2.0
  brasil_fields: ^1.19.0
  mask_text_input_formatter: ^2.9.0
  fluttertoast: ^9.1.0
  drift: ^2.33.0
  drift_flutter: ^0.3.0
  path_provider: ^2.1.5
  optional: ^6.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  rename_app: ^1.6.6
  drift_dev: ^2.33.0
  build_runner: ^2.15.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
