import 'package:flutter/material.dart';

import 'app_colors.dart';

class AppColorScheme {
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: AppColors.green700,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.greenTint,
    onPrimaryContainer: AppColors.green700,
    primaryFixed: AppColors.green400,
    primaryFixedDim: AppColors.green500,
    onPrimaryFixed: AppColors.slate800,
    onPrimaryFixedVariant: AppColors.slate800,
    secondary: AppColors.green500,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.greenTint,
    onSecondaryContainer: AppColors.green700,
    tertiary: AppColors.blue500,
    onTertiary: AppColors.white,
    tertiaryContainer: AppColors.blue100,
    onTertiaryContainer: Color(0xFF1D4ED8),
    error: AppColors.red500,
    onError: AppColors.white,
    errorContainer: AppColors.red100,
    onErrorContainer: Color(0xFFB91C1C),
    surface: AppColors.neutral100,
    onSurface: AppColors.slate800,
    onSurfaceVariant: Color(0xFF4B5563),
    surfaceContainerLowest: AppColors.white,
    surfaceContainerLow: AppColors.neutral100,
    surfaceContainer: AppColors.amber100,
    surfaceContainerHigh: AppColors.green400,
    surfaceContainerHighest: AppColors.green500,
    surfaceDim: Color(0xFFD1FAE5),
    surfaceBright: AppColors.white,
    scrim: Color(0x52000000),
    shadow: AppColors.black,
    outline: Color(0xFFD1D5DB),
    outlineVariant: AppColors.greenTint,
    inverseSurface: AppColors.slate800,
    onInverseSurface: AppColors.neutral100,
    inversePrimary: AppColors.green400,
  );

  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: AppColors.green500,
    onPrimary: AppColors.slate900,
    primaryContainer: AppColors.green700,
    onPrimaryContainer: AppColors.greenTint,
    primaryFixed: AppColors.green400,
    primaryFixedDim: AppColors.teal600,
    onPrimaryFixed: AppColors.slate900,
    onPrimaryFixedVariant: AppColors.greenTint,
    secondary: AppColors.teal600,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.green700,
    onSecondaryContainer: AppColors.green400,
    tertiary: AppColors.blue500,
    onTertiary: AppColors.white,
    tertiaryContainer: Color(0xFF1E3A5F),
    onTertiaryContainer: AppColors.blue100,
    error: AppColors.red500,
    onError: AppColors.slate900,
    errorContainer: Color(0xFF7F1D1D),
    onErrorContainer: AppColors.red100,
    surface: AppColors.slate900,
    onSurface: AppColors.neutral100,
    onSurfaceVariant: Color(0xFF9CA3AF),
    surfaceContainerLowest: AppColors.black,
    surfaceContainerLow: AppColors.slate900,
    surfaceContainer: AppColors.slate800,
    surfaceContainerHigh: AppColors.slate700,
    surfaceContainerHighest: Color(0xFF4B5563),
    surfaceDim: AppColors.slate900,
    surfaceBright: AppColors.slate700,
    scrim: Color(0x80000000),
    shadow: AppColors.black,
    outline: AppColors.slate700,
    outlineVariant: AppColors.slate800,
    inverseSurface: AppColors.neutral100,
    onInverseSurface: AppColors.slate800,
    inversePrimary: AppColors.green700,
  );
}
